[toolchain]
channel = "nightly-2025-02-14"
components = [ "rustfmt", "rustc-dev", "cargo", "clippy", "rust-analyzer", "rust-src", "llvm-tools-preview", "rustc-codegen-cranelift"]
target = ["x86_64-unknown-linux-gnu"]
